# Generated by Django 5.2 on 2025-06-16 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "utility_app",
            "0003_tag_status_alter_tag_created_by_alter_tag_tag_value_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("days", models.JSONField()),
                ("on_time", models.TimeField()),
                ("off_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(to="utility_app.tag")),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField()),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utility_app.schedulegroup",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utility_app.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
