# Generated by Django 5.2 on 2025-06-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utility_app", "0004_schedulegroup_schedulehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PLCConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("port", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "PLC Connection",
                "verbose_name_plural": "PLC Connections",
            },
        ),
    ]
