# Generated by Django 5.2 on 2025-06-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utility_app", "0005_plcconnection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plcconnection",
            options={},
        ),
        migrations.RemoveField(
            model_name="plcconnection",
            name="is_active",
        ),
        migrations.AddConstraint(
            model_name="plcconnection",
            constraint=models.UniqueConstraint(
                fields=("id",), name="unique_plc_connection"
            ),
        ),
    ]
